version: "3.9"

services:

  web:
    build: .
    container_name: FastApiApp
    command: bash -c "
               sleep 20 &&
               alembic upgrade head &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
             "
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: FastApiPostgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"